### ISSUE TITLE
Getting error <path> attribute d: Expected move to path command ('M' or 'm'), "pencil"

### ISSUE THREAD

**Issue by feitla** [Templarian/MaterialDesign-JS#13]
Some of the icons are generating errors such as:
```
Error: <path> attribute d: Expected move to path command ('M' or 'm'), "pencil".
set @ innersvg.js:78
```
`credit-card-outline`, `bank` and a few others are showing similar errors.

**Comment by Templarian** [comment]
Closing this one. If it's still an issue please open on the main repo (the team doesn't monitor the distribution repos).

https://github.com/Templarian/MaterialDesign/
