### ISSUE TITLE
Missing icon: snowmobile

### ISSUE THREAD

**Issue by emiliemarchand** [Templarian/MaterialDesign-JS#16]
Hello! The icon exists on the website but is missing from the library.

This is the usage example from the website:
`import { mdiSnowmobile } from '@mdi/js';`

**Comment by scheepers** [comment]
Hi!
Also finding other missing icons:
mdiMenuRight
mdiArrowRightBold
mdiMenuLeft
mdiArrowLeftBold
mdiConnection

**Comment by scheepers** [comment]
> Hi!
> Also finding other missing icons:
> mdiMenuRight
> mdiArrowRightBold
> mdiMenuLeft
> mdiArrowLeftBold
> mdiConnection

Ok, in my case you have to install and import '@mdi/svg' as well.

**Comment by mririgoyen** [comment]
When we add icons, they appear on the website immediately. However, all the packages don't update until we release, about ever 100 icons or so. If an icon is on the website and you're on the latest package, it hasn't been released yet.

You can either wait for the next package update, download the icon from the website, or hardcode the path data in your application temporarily until the next package is released.

```js
const mdiSnowmobile = 'M20.34 17.93L18.4 16C19.5 15.91 22.66 15.53 22.97 13.36C23 13.12 22.92 12.89 22.78 12.7C22.12 11.82 19.88 9.07 15 5H12V7H14L16 9L12 11L3 10L1 13L5.58 14.38L2.58 16.09C2.22 16.26 1 16.89 1 18.05C1 18.4 1 18.89 1.33 19.32C1.83 20 2.71 20 3 20H9C10.26 20 12.53 19.13 12.93 16H15.59L17.59 18H15V20H20C21.65 20 23 18.65 23 17H21C21 17.43 20.73 17.79 20.34 17.93M9 18H3.25C3.33 17.95 3.41 17.91 3.5 17.87L8.22 15.17L10.92 16C10.58 17.84 9.28 18 9 18Z';
```

**Comment by Templarian** [comment]
This was added in the `6.1.95` release.
