### ISSUE TITLE
Question dynamic import treeshaking

### ISSUE THREAD

**Issue by stephenjason89** [Templarian/MaterialDesign-JS#19]
Hello I have the following code to dynamically import the icon. Only problem is, it doesn't treeshake. Is there a way to make dynamic import treeshaking?

![image](https://user-images.githubusercontent.com/3810177/129450390-74067f1d-b4ca-4a21-a2b8-b68763ce1e95.png)

**Comment by mririgoyen** [comment]
The point of tree-shaking is to remove all code that doesn't get used. If you don't know which icons you will or will not use, how can tree-shaking do it's thing?

**Comment by stephenjason89** [comment]
> The point of tree-shaking is to remove all code that doesn't get used. If you don't know which icons you will or will not use, how can tree-shaking do it's thing?

Yes, you are completely right. It can't, found it the hard way 😅
I came up with a different approach and use all .svg icons file and reference it in an img tag. Instead of importing it, i just change the url.

I'll be closing this issue now 🙂
