### ISSUE TITLE
Break mdi/react : Error: <path> attribute d: Expected number, "mdi-power".

### ISSUE THREAD

**Issue by fabienbranchel** [Templarian/MaterialDesign-JS#2]
The last release (v3.5.94) break the lib mdi/react. It's fine with the previous one (v3.4.93)
I've got following error for each icon in the console : 
Error: <path> attribute d: Expected number, "mdi-power".

Tell me if you need a repro. ;)

**Comment by Templarian** [comment]
Unpublished `@mdi/js@3.5.94`. The build script for the third party packages is broken at the moment. I'll have fixed packages published tonight.

**Comment by Templarian** [comment]
This impacted the `@mdi/angular-material` package also. The `@mdi/font` and `@mdi/svg` were not impacted by this build script update.

Going to add some validation to the build scripts so they will throw an error in the future for invalid data.

**Comment by Templarian** [comment]
Resolved. Thanks again for letting me know.

Going to add a few tests to validate the output.
