### ISSUE TITLE
missing pdf icon

### ISSUE THREAD

**Issue by filippoangileri** [Templarian/MaterialDesign-JS#20]
i not found .mdi-file-pdf (with acrobat logo) on last release why? can u please reput this icon?

**Comment by Templarian** [comment]
@filippoangileri Licensing restricts us from including adobe/acrobat logos. We still have `mdiFilePdfBox`. Part of 6.1.95 was addressing invalid license issues blocking people from using the icon set in production.

https://github.com/Templarian/MaterialDesign/issues/5409
