### ISSUE TITLE
mdiDotsCircle isn't in the package

### ISSUE THREAD

**Issue by Campaio** [Templarian/MaterialDesign-JS#22]
I've tried to use mdiDotsCircle icon, but getting an error
![mdiDotsCircle](https://user-images.githubusercontent.com/18403956/141498688-83739cc2-38f6-4d45-aaec-8d5679544e30.png)

The icon is available for download, but not in the package.

**Comment by Templarian** [comment]
@Campaio `v6.5.95` the very latest version. Might still be on 6.4.95 locally.

**Comment by Campaio** [comment]
You were right, the local version was v6.4.95. But that's weird since I've installed the library on the same day I reported the issue. Anyway, thanks again!
