### ISSUE TITLE
Feature Request: Export the SVG Element Itself

### ISSUE THREAD

**Issue by yuschick** [Templarian/MaterialDesign-JS#25]
## Problem

Using this library to import icons doesn't feel natural. I would expect when importing an icon that it could be used as imported. However, it's quite a burden to always have to create the parent SVG element and its children to be able to use the imported data.

````
import { ABTesting } from '@mdi/js';

return (
  <svg ...allSVGAttributes>
    <path ...pathAttributes d={ABTesting} />
  </svg>
)
`````

While this isn't particularly an issue when bringing this library into a component library which exposes an `Icon` component, it makes using the library outside of that settings very burdensome.

## Request

I would love to be able to import the icons and already have the SVG element with its viewBox and other properties already set to ensure ease of use.

````
import { ABTesting } from '@mdi/js';

return (
  {ABTesting}
)
`````

Outside of creating a React/Framework `Icon` component, is there a way to achieve getting these icons with the svg and path attributes?

**Comment by Templarian** [comment]
Use [`@mdi/react`](https://www.npmjs.com/package/@mdi/react) package. We're trying to keep the `@mdi/js` light as possible as it already has 7k icons and keeps getting new ones.
