### ISSUE TITLE
Icons missing in package

### ISSUE THREAD

**Issue by Vincere1st** [Templarian/MaterialDesign-JS#26]
Hello, it seems icons are missing on package.
I can't find the mdiBriefcaseArrowLeftRight and others briefcase with arrow in the mdi.js file.

Can you fix it please ?

Thanks in advance.

Vincent.

**Comment by MartinX3** [comment]
With the new version we lost mdiEmailSend

After analysing every code change in this new big commit I saw that it got renamed to mdiEmailArrowRight.

**Comment by Templarian** [comment]
Please view the changelog / upgrade guide.

- https://dev.materialdesignicons.com/changelog
- https://dev.materialdesignicons.com/upgrade
