### ISSUE TITLE
The "mdiDeleteClockOutline" icon is pressed to the right edge

### ISSUE THREAD

**Issue by mimaxm** [Templarian/MaterialDesign-JS#27]
The "mdiDeleteClockOutline" icon is pressed to the right edge and downwards. Why isn't it centered like other icons?
![image](https://github.com/Templarian/MaterialDesign-JS/assets/66064167/91753a03-77ab-4177-9cd1-58e3e3bd6e07)

**Comment by Templarian** [comment]
Note use the main https://github.com/Templarian/MaterialDesign repo for issues.
