### ISSUE TITLE
 Uncaught ReferenceError: mdiAccount is not defined     at <anonymous>:1:13

### ISSUE THREAD

**Issue by bojowa** [Templarian/MaterialDesign-JS#5]
npm install @mdi/js
has already install,
this is src/main.js
import { mdiAccount } from '@mdi/js'
do console.log(mdiAccount),it showns that. 
why this?

**Comment by St-Ex** [comment]
You are not providing much information there. What kind of project are you using ? What builder ? Transpiler ?
Have you tried to delete your node_modules and re run an installation ?

```console
npm install
# or
yarn
```

I'm on a @vue/cli project with webpack4 typescript and it works perfectly

```ts
// [...]
import { mdiAccount } from '@mdi/js'
// [...]
console.log(mdiAccount)
// [...]
```
Shows in console
```
M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z
```

**Comment by Templarian** [comment]
Closing this out as this is most likely related to an incorrectly configured project as explained above.

Thanks @St-Ex! 👍
