### ISSUE TITLE
The pack doesn't contain all the icons.

### ISSUE THREAD

**Issue by PanSom** [Templarian/MaterialDesign-JS#6]
The pack doesn't contain all the icons.
For example, I look at https://materialdesignicons.com/ mdiCogOutline is present, but it is not in the package.

**Comment by verbart** [comment]
`mdiCogTransferOutline` also doesn't exist

**Comment by Templarian** [comment]
@PanSom @verbart We're getting ready for 5.0 this means consolidating breaking changes. We do monthly releases, so expect 5.0 to be out within the next 2 weeks.

Learn More: https://github.com/Templarian/MaterialDesign/issues/4901

**Comment by verbart** [comment]
mdiClipboardEditOutline not exist in v5.3.45
