### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by UglyHobbitFeet** [Templarian/MaterialDesign-JS#7]
I'm getting errors that this one no longer exists as of 5.0.45
mdi-text-box-multiple-outline

Looking at the mdi.js file confirms that

**Comment by Templarian** [comment]
@UglyHobbitFeet Can you make sure you ran `npm install` after updating to v5?

https://raw.githubusercontent.com/Templarian/MaterialDesign-JS/master/mdi.js shows `mdiTextBoxMultipleOutline`.

**Comment by UglyHobbitFeet** [comment]
I thought I did that, but possibly not.  Works now. Thanks!
