### ISSUE TITLE
Missing icon: view-column-outline

### ISSUE THREAD

**Issue by afberg** [Templarian/MaterialDesign-JS#8]
The webpage example says to use the following string to import the above mentioned icon. 
```javascript
import { mdiViewColumnOutline } from '@mdi/js';
```

However, it does not exist in the repository.

**Comment by Templarian** [comment]
@afberg That was added the other day and won't make it until the `5.3.xx` release in probably 2 weeks.

The `5.2.45` is going out tonight or tomorrow. But will not contain this as we release in batches of 100.

**Comment by Templarian** [comment]
btw: https://dev.materialdesignicons.com/history
